### PR TITLE
Fix (hide from defaults not hiding wallets)

### LINKED ISSUE #274: hideFromDefaults option doesnt do anything
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CeloProvider has a `connectModal.providersOptions.hideFromDefaults` which is designed to hide default wallet connections showing up in the modal. However they are still showing up. 

### Steps to reproduce

```
<CeloProvider connectModal={{
            providersOptions: {
              hideFromDefaults: [
                SupportedProviders.CeloDance,
                SupportedProviders.Ledger,
              ],
            },
          }} />
          
```          

### Expected behavior

When I provide `true` none should show

When I provide an array of SupportedProviders[] those should not show

### Screenshot

_No response_

### Where is the problem happening?

Both

### Environment

all

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

4.0.0

### What wallet were you using?

n/a

### What is the dApp URL? (if applicable)

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aaronmgdr**
Passing in the `hideFromDefaults` option was having no effect on what was showing. 

fixes #274

### CODE REVIEW

File: packages/react-celo/src/utils/useProviders.ts [hunk 1]
```diff
@@ -44,18 +45,23 @@ export function getRecent(): Maybe<Provider> {
...
   wallets: WalletEntry[] = [],
+  allScreens: Record<string, React.FC<ConnectorProps>>,
   sort = defaultProviderSort,
   search?: string
 ) {
   const record: Record<string, Provider> = useMemo(
     () => ({
-      ...PROVIDERS,
+      ...Object.keys(allScreens).reduce((all, current) => {
+        // @ts-ignore
```
Comment (nicolasbrugneaux) [inline packages/react-celo/src/utils/useProviders.ts:55]: not the biggest fan, can we type this better?

Comment (aaronmgdr) [reply packages/react-celo/src/utils/useProviders.ts:55]: oh right. yeah had to go to appt and just wanted to get this up. 

probably can do better

**Review by dckesler — APPROVED** [review]
