### PR TITLE
dont ask metamask to unlock if we are already connected and ressurecting

### LINKED ISSUE #295: When metamask is locked, should not open the popup asking me to unlock
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If I've connected metamask before and I have it locked, when entering the website it asks me to unlock.

### Steps to reproduce

1. go to https://react-celo.vercel.app/
2. connect with metamask
3. lock metamask
4. refresh the page

### Expected behavior

After step 4. (refreshing the page), the user should not be asked to unlock metamask.

### Screenshot

_No response_

### Where is the problem happening?

Desktop

### Environment

browser: Brave
os: macOS 12.4

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

4.0.1-dev

### What wallet were you using?

metamask

### What is the dApp URL? (if applicable)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aaronmgdr**
When resurrecting metaMask and metaMask locked dont request the account (instead use the address found in local storage). This stops the need to unlock metaMask right away when loading the site. 

Fixes #295

### CODE REVIEW

File: packages/react-celo/src/connectors/injected.ts [hunk 1]
```diff
@@ -32,23 +32,29 @@ export default class InjectedConnector
...
   }
 
-  async initialise(): Promise<this> {
+  async initialise(lastUsedAddress?: string): Promise<this> {
     if (this.initialised) {
       return this;
     }
 
+    // is this a bad idea?
+    let defaultAccount = lastUsedAddress;
```
Comment (nicolasbrugneaux) [inline packages/react-celo/src/connectors/injected.ts:41]: Idk, it feels like a bad idea but it probably isn't

Comment (aaronmgdr) [reply packages/react-celo/src/connectors/injected.ts:41]: yeah

File: packages/react-celo/src/connectors/injected.ts [hunk 2]
```diff
@@ -33,23 +33,28 @@ export default class InjectedConnector
...
     this.type = isMetaMask ? WalletTypes.MetaMask : WalletTypes.Injected;
-
-    const [defaultAccount] = await ethereum.request({
-      method: 'eth_requestAccounts',
-    });
-
+    const metamask = ethereum._metamask;
+    const isUnlocked = isMetaMask && (await metamask?.isUnlocked());
+    const isConnected = ethereum.isConnected && ethereum.isConnected();
+    if (isUnlocked || !isConnected || !lastUsedAddress) {
```
Comment (dckesler) [inline packages/react-celo/src/connectors/injected.ts:53]: If you change this to use `defaultAccount` instead of `lastUsedAddress` you can get rid of the `as string` casting below.

File: packages/react-celo/src/connectors/injected.ts [hunk 3]
```diff
@@ -61,17 +66,17 @@ export default class InjectedConnector
     ethereum.on('chainChanged', this.onChainChanged);
     ethereum.on('accountsChanged', this.onAccountsChanged);
 
-    this.newKit(web3 as unknown as Web3Type, defaultAccount);
+    this.newKit(web3 as unknown as Web3Type, defaultAccount as string);
```
Comment (dckesler) [inline packages/react-celo/src/connectors/injected.ts:69]: So this one will go away

File: packages/react-celo/src/connectors/injected.ts [hunk 4]
```diff
@@ -61,17 +66,17 @@ export default class InjectedConnector
...
 
     const walletChainId = await ethereum.request({ method: 'eth_chainId' });
 
     this.initialised = true;
 
     this.emit(ConnectorEvents.CONNECTED, {
       walletType: this.type,
-      walletChainId: parseInt(walletChainId, 16),
-      address: defaultAccount,
+      address: defaultAccount as string,
```
Comment (dckesler) [inline packages/react-celo/src/connectors/injected.ts:77]: And this one

**Review by dckesler — CHANGES_REQUESTED** [review]

**Review by dckesler — APPROVED** [review]
